repomas/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField
from wtforms.validators import DataRequired, EqualTo, Email, Length, ValidationError

from repomas.models import User


class UserRegistrationForm(FlaskForm):
    first_name = StringField('First Name', validators=[DataRequired()])
    last_name = StringField('Last Name', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    # username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=6, max=20)])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(),
                                                                     EqualTo('password')])

    submit = SubmitField('Register')

    @staticmethod
    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('That Email is taken. Please choose a different one.')


class UserLoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=6, max=20)])

    submit = SubmitField('Login')


class UserUpdateForm(FlaskForm):
    first_name = StringField('First Name', validators=[DataRequired()])
    last_name = StringField('Last Name', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    username = StringField('Username', validators=[DataRequired()])

    submit = SubmitField('Update Profile ')

repomas/user/__init__.py
from sys import prefix
from flask import Blueprint

user = Blueprint('user', __name__, url_prefix="/user")

from . import views

repomas/user/views.py
from flask import render_template, redirect, url_for, flash
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from .forms import UserRegistrationForm, UserLoginForm
from ..utils import generate_uuid

from repomas import db
from repomas.models import User
from . import user


@user.route('/registration', methods=['POST', 'GET'])
def registration():
    user_count = User.query.count()
    form = UserRegistrationForm()
    if form.validate_on_submit():
        if user_count == 0:
            print("success")
            hashed_pass = generate_password_hash(form.password.data)
            admin = User(first_name=form.first_name.data, last_name=form.last_name.data,
                         email=form.email.data, password=hashed_pass,
                         uuid=generate_uuid(), is_admin=True, is_active=True
                         )

            db.session.add(admin)
            db.session.commit()

            flash("Administrator Successfully Added", "success")
            return redirect(url_for('user.login'))
        else:
            hashed_pass = generate_password_hash(form.password.data)
            new_user = User(first_name=form.first_name.data, last_name=form.last_name.data,
                            email=form.email.data, password=hashed_pass, uuid=generate_uuid())
            print(new_user)
            db.session.add(new_user)
            db.session.commit()

            flash("User Successfully Added", "success")
            return redirect(url_for('user.login'))

    return render_template('user/registration.html', form=form, user_count=user_count)


@user.route('/login', methods=['POST', 'GET'])
def login():
    users = User.query.all()

    if len(users) == 0:
        return redirect(url_for('user.registration'))
    form = UserLoginForm()
    if form.validate_on_submit():

        existing_user = User.query.filter_by(email=form.email.data).first()

        if existing_user and existing_user.is_admin and \
                check_password_hash(existing_user.password, form.password.data):

            login_user(existing_user)
            flash("Login Success", "success")
            return redirect(url_for('admin.dashboard'))
        elif existing_user and not existing_user.is_admin and \
                check_password_hash(existing_user.password, form.password.data):
            login_user(existing_user)
            flash("Login Success", "success")
            return redirect(url_for('user.dashboard'))
        else:
            flash("Wrong credentials!!. Please check your email and password and try again!",
                  "danger")
            return redirect(url_for('user.login'))

    return render_template('user/login.html', form=form)


@user.route('/dashboard', methods=['GET', 'POST'])
@login_required
def dashboard():
    return render_template("user/dashboard.html", title="User Dashboard")


@user.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    flash('You have successfully Logged Out', 'success')
    return redirect(url_for('user.login'))

repomas/templates/user/dashboard.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <h1 class="text-center">Welcome to User Dashboard</h1>
        <div class="row text-center mt-5">
            <div class="col-3">
                <div class="card">
                    <a href="{{ url_for('student.add_student')}}" class="btn btn-success">Add Student</a>
                </div>
            </div>
            <div class="col-3">
                <div class="card">
                    <a href="{{ url_for('student.all_students')}}" class="btn btn-success">Show Students</a>
                </div>
            </div>
            <div class="col-3">
                <div class="card">
                    <a href="" class="btn btn-success">Profile</a>
                </div>
            </div>
            <div class="col-3">
                <div class="card">
                    <a href="{{ url_for('user.logout')}}" class="btn btn-outline-info">Logout</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

repomas/templates/user/login.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <a href="{{ url_for('home.home')}}" class="card bg-primary text-center text-white" 
    style="max-width: 13rem; height: 2rem; text-decoration: none;">Home</a> 
    <div class="card mt-5">
        <div class="card-body">
            <form action="" method="POST" role="form">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">User</legend>
                    <div class="form-group">
                        {{ form.email.label(class="form-control-label") }}
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.password.label(class="form-control-label") }}
                        {% if form.password.errors %}
                            {{ form.password(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.password(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                </fieldset>
                <div class="form-group mt-2">
                    {{ form.submit(class="btn btn-outline-info") }}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

repomas/templates/user/registration.html
{% extends "base.html" %}
{% block content %}
<div class="card">
<div class="card-body">
    <form action="" method="POST" role="form">
        {{ form.csrf_token }}
        <fieldset class="form-group">
            {% if user_count >= 1 %}
                 <legend class="border-bottom mb-4">User Registration</legend>
            {% else %}
                <legend class="border-bottom mb-4">First Time Registration For Administrator</legend>
            {% endif %}
            <div class="form-group">
                <div class="row">
                    <div class="col-6">
                        {{ form.first_name.label(class="form-control-label") }}
                        {% if form.first_name.errors %}
                            {{ form.first_name(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.first_name.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.first_name(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="col-6">
                        {{ form.last_name.label(class="form-control-label") }}
                        {% if form.last_name.errors %}
                            {{ form.last_name(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.last_name.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.last_name(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.confirm_password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group mt-2">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
</div>
{% endblock %}