repomas/student/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField
from wtforms.fields.html5 import DateField
from wtforms.validators import ValidationError, DataRequired

from repomas.models import Student


class StudentRegistrationForm(FlaskForm):

    first_name = StringField('First Name', validators=[DataRequired()])
    last_name = StringField('Last Name', validators=[DataRequired()])
    admission = StringField('Admission Number', validators=[DataRequired()])
    birthdate = DateField('Date of Birth', validators=[DataRequired()])
    zipcode = IntegerField('Zip Code', validators=[DataRequired()])
    county  = StringField('County', validators=[DataRequired()])
    ward = StringField('Ward', validators=[DataRequired()])

    submit = SubmitField('Save Student')

    def validate_admission(self, admission):
        student = Student.query.filter_by(admission=admission.data).first()
        if student:
            raise ValidationError('That admission number is taken. Please choose a different one.')

    


class StudentUpdateForm(FlaskForm):

    first_name = StringField('First Name', validators=[DataRequired()])
    last_name = StringField('Last Name', validators=[DataRequired()])
    admission = StringField('Admission Number', validators=[DataRequired()])
    birthdate = DateField('Date of Birth', validators=[DataRequired()])
    zipcode = IntegerField('Zip Code', validators=[DataRequired()])
    county  = StringField('County', validators=[DataRequired()])
    ward = StringField('Ward', validators=[DataRequired()])

    submit = SubmitField('Update Details')

repomas/student/__init__.py
from flask import Blueprint

student = Blueprint('student', __name__)

from . import views

repomas/student/views.py
from datetime import datetime as dt
from flask import flash, url_for, abort, request
from flask_login import login_required
from repomas.student.forms import StudentRegistrationForm, StudentUpdateForm
from flask import render_template, redirect
from repomas import db
from repomas.models import MedicalStatus, Student
from . import student

@student.route('/student/registration', methods=['POST', 'GET'])
@login_required
def add_student():
    form = StudentRegistrationForm()
    if form.validate_on_submit():

        student = Student(first_name=form.first_name.data, last_name=form.last_name.data, 
                    admission=form.admission.data, birthdate=form.birthdate.data, zipcode=form.zipcode.data,
                    county=form.county.data, ward=form.ward.data)
        db.session.add(student)
        db.session.commit()
        flash("Successfully Added a student", "success")
        return redirect(url_for('user.dashboard'))

    return render_template('student/register.html', form=form, title='Student Registration')

@student.route('/student/all', methods=['POST', 'GET'])
def all_students():
    students = Student.query.all()
    nums = Student.query.count()
    return render_template('student/students_table.html', title='Students', students=students, nums=nums)


@student.route('/student/<int:student_id>', methods=['POST', 'GET'])
@login_required
def student_detail(student_id):
    student = Student.query.get_or_404(student_id)
    medrec = db.session.query(MedicalStatus.height, MedicalStatus.weight, MedicalStatus.disabled,
                                MedicalStatus.diagnosis, MedicalStatus.underlying, MedicalStatus.drug,
                                MedicalStatus.outcome).join(Student, Student.id == MedicalStatus.student_id).filter_by(id=student_id).first()
    currentyr = dt.utcnow()
    return render_template('student/student_details.html', 
    title='Student', student=student, year=currentyr, medrec=medrec)

@student.route('/students/<int:student_id>/update/', methods=['POST', 'GET'])
@login_required
def update_student(student_id):

    student = Student.query.get_or_404(student_id)

    if not student:
        abort(403)

    form = StudentUpdateForm()

    if form.validate_on_submit():

        student.first_name = form.first_name.data
        student.last_name = form.last_name.data
        student.admission = form.admission.data
        student.birthdate = form.birthdate.data
        student.zipcode = form.zipcode.data
        student.county = form.county.data
        student.ward = form.ward.data

        db.session.commit()

        flash("Successfully Updated the student", "success")
        return redirect(url_for('student.all_students'))

    elif request.method == 'GET':

        form.first_name.data = student.first_name
        form.last_name.data = student.last_name
        form.admission.data = student.admission
        form.birthdate.data = student.birthdate
        form.zipcode.data = student.zipcode
        form.county.data = student.county
        form.ward.data = student.ward

    return render_template('student/register.html', title='Student Update', 
                                    legend="Update Student Details", form=form)

@student.route('/student/<int:student_id>/delete/', methods=['POST', 'GET'])
@login_required
def delete_student(student_id):
    student = Student.query.get_or_404(student_id)
    if student:
        db.session.delete(student)
        db.session.commit()
        flash("Successfully deleted the student from the database", "success")
        return redirect(url_for('student.all_students'))
    else:
        flash("The student does not exist", "warning")
        return redirect(url_for('student.all_students')) 

repomas/templates/student/register.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <a href="{{ url_for('admin.dashboard')}}" class="card bg-primary text-center text-white" 
    style="max-width: 5rem; height: 3rem; text-decoration: none; padding: 10px;">Home</a>
    <div class="card mt-4">
    <div class="card-body">
        <form action="" method="POST" role="form">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                {% if legend %}
                    <legend class="border-bottom mb-4">Add a Student</legend>
                {% else%}
                    <legend class="border-bottom mb-4">{{ legend }}</legend>
                {% endif %}
                <div class="form-group">
                    <div class="row">
                        <div class="col-6">
                            {{ form.first_name.label(class="form-control-label") }}
                            {% if form.first_name.errors %}
                                {{ form.first_name(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.first_name.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.first_name(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                        <div class="col-6">
                            {{ form.last_name.label(class="form-control-label") }}
                            {% if form.last_name.errors %}
                                {{ form.last_name(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.last_name.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.last_name(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-4">
                        {{ form.admission.label(class="form-control-label") }}
                        {% if form.admission.errors %}
                            {{ form.admission(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.admission.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.admission(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group col-4">
                        {{ form.birthdate.label(class="form-control-label") }}
                        {% if form.birthdate.errors %}
                            {{ form.birthdate(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.birthdate.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.birthdate(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group col-4">
                        {{ form.zipcode.label(class="form-control-label") }}
                        {% if form.zipcode.errors %}
                            {{ form.zipcode(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.zipcode.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.zipcode(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-6">
                        {{ form.county.label(class="form-control-label") }}
                        {% if form.county.errors %}
                            {{ form.county(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.county.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.county(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group col-6">
                        {{ form.ward.label(class="form-control-label") }}
                        {% if form.ward.errors %}
                            {{ form.ward(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.ward.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.ward(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                </div>
            </fieldset>
            <div class="form-group mt-2">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    </div>
</div>
{% endblock %}

repomas/templates/student/student_details.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <a href="{{ url_for('student.all_students')}}" class="card bg-primary text-center text-white" 
            style="max-width: 13rem; height: 2rem; text-decoration: none;">Students List</a>  
        </div>
        <div class="col-6">
            <a href="{{ url_for('med.add_record', student_id=student.id)}}" class="card bg-primary text-center text-white" 
            style="max-width: 13rem; height: 2rem; text-decoration: none; ">Add {{ student.first_name }}'s medical record</a>
        </div>
    </div>
    <div class="card mt-4">
        <h2 class="text-center">Medical Records</h2><hr>
        <div class="card-body">
            <h3 class="card-title">Name: {{ student.first_name + " " + student.last_name }}</h3>
            <div class="row">
                <p class="col-3">Admission: {{ student.admission }}</p>
                <p class="col-3">Age: {{ (year-student.birthdate).days//365 }} years</p>
                <p class="col-3">Zipcode: {{ student.zipcode }}</p>
                <p class="col-3">County: {{ student.county }}</p>
                <p class="col-3">Ward: {{ student.county }}</p>
            </div>
        </div>
        <div class="card-body">
            <h3 class="card-title  text-center">Medical History</h3>
            {% if not medrec %}
                <p class="bg-primary text-white text-center fw-bold fs-3 p-3">There are no Medical history for the student!</p>
            {% else%}
             <div class="row">
                 <p class="col-4">Height {{ medrec.height}}</p>
                 <p class="col-4">Weight: {{ medrec.weight }}</p>
                 <p class="col-3">BMI: {{ medrec.weight/(medrec.height**2)}}</p>
                 {% if medrec.disabled == True %}
                    <p class="col-4">Disability: Disabled</p>
                 {% else %}
                    <p class="col-4">Disability: No Disability</p>
                 {% endif %}
             </div>
            <div class="row">
                 <p class="col-8">Diagnosis: {{ medrec.diagnosis }}</p>
                 <p class="col-4">Underlying Condition: {{ medrec.underlying }}</p>
            </div>
            <div class="row">
                 <p class="col-3">Drug Prescribed: {{ medrec.drug }} </p>
                 <p class="col-3">Outcome: {{ medrec.outcome }}</p>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

repomas/templates/student/students_table.html
{% extends "base.html" %}
{% block content %}
<div class="content">
    <div class="container-fluid">
            <div class="row">
                <div class="col-6">
                    <a href="{{ url_for('admin.dashboard')}}" class="card bg-primary text-center text-white" 
                    style="max-width: 13rem; height: 2rem; text-decoration: none;">Home</a>  
                </div>
                <div class="col-6">
                    <a href="{{ url_for('student.add_student')}}" class="card bg-primary text-center text-white" 
                    style="max-width: 13rem; height: 2rem; text-decoration: none; ">Add another student</a>
                </div>
            </div>  
        </div>
        <div class="row mt-4">
            <div class="col-md-12">
                <div class="card">
                    <div class="header">
                        <h3 class="title text-center">Registered Students</h3>
                        <hr>
                    </div>
                    <div class="content table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <th>Name</th>
                                <th>Admission Number</th>
                                <th>Date of Birth</th>
                                <th>Zipcode</th>
                                <th>County</th>
                                <th>Ward</th>
                                <th>Action</th>
                            </thead>
                            <tbody>
                                    {% for stud in students %}
                                        
                                            <tr class="table-row">
                                                <td>
                                                    <a href="{{ url_for('student.student_detail', student_id=stud.id)}}" style="text-decoration: none;">
                                                        {{ stud.first_name + " " + stud.last_name}}
                                                    </a>
                                                </td>
                                                <td>{{ stud.admission }}</td>
                                                <td>{{ stud.birthdate.strftime("%Y/%m/%d")}}</td>
                                                <td>{{ stud.zipcode}}</td>
                                                <td>{{ stud.county}}</td>
                                                <td>{{ stud.ward}}</td>
                                                <td>
                                                    <a href="{{ url_for('student.update_student', student_id=stud.id)}}" class="btn btn-primary">Edit</a>
                                                    |
                                                    <a href="{{ url_for('student.delete_student', student_id=stud.id)}}" class="btn btn-danger">Delete</a>
                                                </td>
                                            </tr>
                                            
                                    {% endfor %}
                            </tbody>
                        </table>
                        <p>Total students are {{ nums }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}